################################################################################
FROM ubuntu:22.04
################################################################################

ARG GPU_DEVICE_TARGETS="gfx908,gfx90a,gfx942,gfx950,gfx1030,gfx1100,gfx1101,gfx1102,gfx1200,gfx1201"
ENV GPU_DEVICE_TARGETS=${GPU_DEVICE_TARGETS}
ENV TF_ROCM_AMDGPU_TARGETS=${GPU_DEVICE_TARGETS}

# Setup ci users/groups
RUN groupadd --gid 109 render
RUN groupadd --gid 114 engflow
RUN useradd --home-dir /home/engflow --create-home --uid 121 --gid 114 --groups render,video engflow

# Install ROCM
ARG ROCM_VERSION=6.2.0
ARG CUSTOM_INSTALL
ARG ROCM_PATH=/opt/rocm-${ROCM_VERSION}
ENV ROCM_PATH=${ROCM_PATH}
COPY ${CUSTOM_INSTALL} /${CUSTOM_INSTALL}
COPY setup.rocm.sh /setup.rocm.sh
COPY devel.packages.xla.ci.txt /devel.packages.rocm.txt
RUN /setup.rocm.sh $ROCM_VERSION jammy

# - bazelisk: always use the correct bazel version
RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64 -O /usr/local/bin/bazel && chmod +x /usr/local/bin/bazel

# Setup build and environment
COPY devel.bashrc /root/.bashrc

# Setup ENV variables for tensorflow pip build
ENV TF_NEED_ROCM=1
ENV TF_ROCM_GCC=1
ENV ROCM_TOOLKIT_PATH=${ROCM_PATH}
