################################################################################
ARG DISTRO_IMG
FROM ${DISTRO_IMG:-'debian:bookworm'} as runtime
################################################################################

ARG GPU_DEVICE_TARGETS="gfx908,gfx90a,gfx942,gfx950,gfx1030,gfx1100,gfx1101,gfx1102,gfx1200,gfx1201"
ENV GPU_DEVICE_TARGETS=${GPU_DEVICE_TARGETS}

# Install build dependencies
COPY setup.packages.sh /setup.packages.sh
COPY runtime.packages.txt /runtime.packages.txt
RUN /setup.packages.sh /runtime.packages.txt

# Install ROCM
ARG ROCM_VERSION=6.2.0
ARG CUSTOM_INSTALL
ARG ROCM_PATH=/opt/rocm-${ROCM_VERSION}
ENV ROCM_PATH=${ROCM_PATH}
COPY ${CUSTOM_INSTALL} /${CUSTOM_INSTALL}
COPY setup.rocm.sh /setup.rocm.sh
COPY devel.packages.rocm.txt /devel.packages.rocm.txt
RUN /setup.rocm.sh $ROCM_VERSION bookworm

# All lines past this point are reset when $CACHEBUSTER is set. We need this
# for Python specifically because we install some nightly packages which are
# likely to change daily.
ARG CACHEBUSTER=0
RUN echo $CACHEBUSTER

# Setup ENV variables for tensorflow pip build
ENV TF_NEED_ROCM=1
ENV TF_ROCM_GCC=1
ENV ROCM_TOOLKIT_PATH=${ROCM_PATH}

# Setup Python environment
ARG PYTHON_VERSION
COPY setup.build-python_ubuntu.sh /setup.build-python_ubuntu.sh
COPY devel.requirements.txt /devel.requirements.txt
RUN /setup.build-python_ubuntu.sh $PYTHON_VERSION /devel.requirements.txt

# Install TensorFlow nightly wheel
ARG TF_PKGS_DIR=tmp/my-packages
RUN mkdir -p /${TF_PKGS_DIR}
ARG TF_PKG_LOC=http://aus-navi3x-03.amd.com:8080/job/tensorflow/job/nightly-build-whl/lastSuccessfulBuild/artifact/develop-upstream/packages-${PYTHON_VERSION}
# CI names the nighlty wheel as the latest release version + 1
ARG TF_VERSION=2.22.0
ARG TENSORFLOW_PACKAGE
RUN WHEEL="${TENSORFLOW_PACKAGE}"; \
    if [ -z "${WHEEL}" ]; then \
      CP_VERS=$(echo $PYTHON_VERSION | sed 's/\.//g'); \
      WHEEL="tensorflow-${TF_VERSION}.dev0+selfbuilt-cp${CP_VERS}-cp${CP_VERS}-linux_x86_64.whl"; \
    fi; \
    wget ${TF_PKG_LOC}/${WHEEL} -O /${TF_PKGS_DIR}/${WHEEL} && \
    pip install --no-cache-dir /${TF_PKGS_DIR}/${WHEEL}

RUN echo 'ALL ALL=NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd

ARG TF_TESTING_FL
ENV TF_TESTING_FL=${TF_TESTING_FL}
ARG DWLD_TF_SRC_CMD
RUN if [ -n "${DWLD_TF_SRC_CMD}" ]; then eval "${DWLD_TF_SRC_CMD}"; fi
RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64 -O /usr/local/bin/bazel && \
    chmod +x /usr/local/bin/bazel
RUN git clone https://github.com/tensorflow/models.git
RUN git clone https://github.com/tensorflow/examples.git
RUN git clone https://github.com/tensorflow/autograph.git
RUN git clone https://github.com/tensorflow/benchmarks.git